Mobile Client for Android: com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes Class Reference
com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes Class Reference
Public Member Functions
GNAlbumIdAttributes ()
GNAlbumIdAttributes (String inFilePath)
String getGenre ()
void setGenre (String genre)
String getIdentifier ()
void setIdentifier (String identifier)
String getGnId ()
void setGnId (String gnId)
String getTrackNumber ()
void setTrackNumber (String trackNumber)
String getAlbumTitle ()
void setAlbumTitle (String albumTitle)
String getTrackTitle ()
void setTrackTitle (String trackTitle)
String getArtist ()
void setArtist (String artist)
String getFilePath ()
void setFilePath (String filePath)
String getFingerprintData ()
void setFingerprintData (String fingerprintData)
Detailed Description
Container class for the metadata fetched from
a file for AlbumId operations.
Definition at line 17 of file GNAlbumIdAttributes.java.
Constructor & Destructor Documentation
com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.GNAlbumIdAttributes ()
Definition at line 21 of file GNAlbumIdAttributes.java.
References com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setAlbumTitle(), com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setArtist(), com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setFilePath(), com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setFingerprintData(), com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setGenre(), com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setGnId(), com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setIdentifier(), com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setTrackNumber(), and com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setTrackTitle().
com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.GNAlbumIdAttributes (String inFilePath)
Definition at line 49 of file GNAlbumIdAttributes.java.
References com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setAlbumTitle(), com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setArtist(), com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setFilePath(), com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setFingerprintData(), com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setGenre(), com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setGnId(), com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setIdentifier(), com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setTrackNumber(), and com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setTrackTitle().
Member Function Documentation
String com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.getAlbumTitle ()
Returns the album title of the music file.
Returns
Music file album title
Definition at line 279 of file GNAlbumIdAttributes.java.
String com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.getArtist ()
Returns the artist of the music file.
Returns
Music file artist
Definition at line 359 of file GNAlbumIdAttributes.java.
String com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.getFilePath ()
Returns the file path of the music file.
Returns
Music file path
Definition at line 403 of file GNAlbumIdAttributes.java.
String com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.getFingerprintData ()
Returns the fingerprint data of the music file.
Returns
Music file fingerprint data
Definition at line 437 of file GNAlbumIdAttributes.java.
String com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.getGenre ()
Returns the genre of the music file.
Returns
Music file genre
Definition at line 105 of file GNAlbumIdAttributes.java.
String com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.getGnId ()
Returns the gnId of the music file.
Returns
Music file gnId
Definition at line 175 of file GNAlbumIdAttributes.java.
String com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.getIdentifier ()
Returns the Identifier of the music file.
Returns
Music file Identifier
Definition at line 139 of file GNAlbumIdAttributes.java.
String com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.getTrackNumber ()
Returns the track number of the music file.
Returns
Music file track number
Definition at line 247 of file GNAlbumIdAttributes.java.
String com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.getTrackTitle ()
Returns the track title of the music file.
Returns
Music file track title
Definition at line 323 of file GNAlbumIdAttributes.java.
void com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setAlbumTitle (String albumTitle)
Sets the value of the album title.
Parameters
albumTitle
Definition at line 305 of file GNAlbumIdAttributes.java.
Referenced by com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.GNAlbumIdAttributes().
void com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setArtist (String artist)
Sets the value of the artist.
Parameters
artist
Definition at line 385 of file GNAlbumIdAttributes.java.
Referenced by com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.GNAlbumIdAttributes().
void com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setFilePath (String filePath)
Sets the value of the file path.
Parameters
filePath
Definition at line 419 of file GNAlbumIdAttributes.java.
Referenced by com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.GNAlbumIdAttributes().
void com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setFingerprintData (String fingerprintData)
Sets the value of the fingerprint data.
Parameters
fingerprintData
Definition at line 451 of file GNAlbumIdAttributes.java.
Referenced by com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.GNAlbumIdAttributes().
void com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setGenre (String genre)
Sets the value of the genre.
Parameters
genre
Definition at line 123 of file GNAlbumIdAttributes.java.
Referenced by com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.GNAlbumIdAttributes().
void com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setGnId (String gnId)
Sets the value of the gnId.
Parameters
gnId
Definition at line 191 of file GNAlbumIdAttributes.java.
Referenced by com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.GNAlbumIdAttributes().
void com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setIdentifier (String identifier)
Sets the value of the identifier.
Parameters
identifier
Definition at line 157 of file GNAlbumIdAttributes.java.
Referenced by com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.GNAlbumIdAttributes().
void com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setTrackNumber (String trackNumber)
Sets the value of the track number.
Parameters
trackNumber
Definition at line 261 of file GNAlbumIdAttributes.java.
Referenced by com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.GNAlbumIdAttributes().
void com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.setTrackTitle (String trackTitle)
Sets the value of the track title.
Parameters
trackTitle
Definition at line 341 of file GNAlbumIdAttributes.java.
Referenced by com.gracenote.mmid.MobileSDK.GNAlbumIdAttributes.GNAlbumIdAttributes().
How can we improve this topic?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Mon Jun 3 2013 13:26:05.