Mobile Client for Android: com.gracenote.mmid.MobileSDK.GNCoverArt Class Reference
com.gracenote.mmid.MobileSDK.GNCoverArt Class Reference
Public Member Functions
String toString ()
Public Member Functions inherited from com.gracenote.mmid.MobileSDK.GNImage
GNImage (byte[] inData, String inSize, String inMimeType)
GNImage (String inUrl)
byte[] getData ()
String getSize ()
String getMimeType ()
String getUrl ()
String toString ()
Detailed Description
Container class for album cover art.
Definition at line 17 of file GNCoverArt.java.
Member Function Documentation
String com.gracenote.mmid.MobileSDK.GNCoverArt.toString ()
Returns a string that describes the GNCoverArt instance.
Returns
String describing the GNCoverArt instance.
Definition at line 47 of file GNCoverArt.java.
References com.gracenote.mmid.MobileSDK.GNImage.getData(), com.gracenote.mmid.MobileSDK.GNImage.getMimeType(), and com.gracenote.mmid.MobileSDK.GNImage.getSize().
How can we improve this topic?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Mon Jun 3 2013 13:26:05.