Mobile Client for Android: com.gracenote.mmid.MobileSDK.GNSearchResultReady Interface Reference
com.gracenote.mmid.MobileSDK.GNSearchResultReady Interface Reference
Inherited by com.gracenote.mmid.MobileSDK.GNRecognizeStream.RecognizePCMOneFPTask, and com.gracenote.mmid.MobileSDK.GNRecognizeStream.RecognizePCMTwoFPTask.
Public Member Functions
void GNResultReady (GNSearchResult result)
Detailed Description
Interface that enables delivery of
results to an application.
Applications using recognition or search operations
need to create an object that implements this interface and provide an instance
of that object when invoking the operation.
Mobile Client delivers the result of the operation by calling interface
method GNResultReady.
Definition at line 25 of file GNSearchResultReady.java.
Member Function Documentation
void com.gracenote.mmid.MobileSDK.GNSearchResultReady.GNResultReady (GNSearchResult result)
Method called by Mobile Client to deliver the result of a recognition or
search operation.
The application can process the result in the body of this function.
Parameters
result Object containing the associated operation's result
Referenced by com.gracenote.mmid.MobileSDK.GNOperations.albumIdDirectory(), com.gracenote.mmid.MobileSDK.GNOperations.albumIdFile(), com.gracenote.mmid.MobileSDK.GNOperations.albumIdList(), com.gracenote.mmid.MobileSDK.GNOperations.fetchByAlbumId(), com.gracenote.mmid.MobileSDK.GNOperations.fetchByTrackId(), com.gracenote.mmid.MobileSDK.GNOperations.searchByLyricFragment(), and com.gracenote.mmid.MobileSDK.GNOperations.searchByText().
How can we improve this topic?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Mon Jun 3 2013 13:26:06.