Mobile Client for Android: com.gracenote.mmid.MobileSDK.GNOperations Class Reference
com.gracenote.mmid.MobileSDK.GNOperations Class Reference
Classes
enum Opeartion
Static Public Member Functions
static void fingerprintMIDStreamFromMic (GNFingerprintResultReady resultReady, GNConfig config)
static void fingerprintMIDStreamFromPcm (GNFingerprintResultReady resultReady, GNConfig config, GNSampleBuffer sampleBuffer)
static void fingerprintMIDFileFromPcm (GNFingerprintResultReady resultReady, GNConfig config, GNSampleBuffer sampleBuffer)
static void fingerprintMIDFileFromFile (GNFingerprintResultReady resultReady, GNConfig config, String filename)
static void recognizeMIDStreamFromMic (GNSearchResultReady resultReady, GNConfig config)
static void recognizeMIDStreamFromPcm (GNSearchResultReady resultReady, GNConfig config, GNSampleBuffer sampleBuffer)
static void recognizeMIDFileFromPcm (GNSearchResultReady resultReady, GNConfig config, GNSampleBuffer sampleBuffer)
static void recognizeMIDFileFromFile (GNSearchResultReady resultReady, GNConfig config, String filename)
static void albumIdFile (GNSearchResultReady resultReady, GNConfig config, List< String > filePaths)
static void albumIdDirectory (GNSearchResultReady resultReady, GNConfig config, String directoryPath)
static void albumIdList (GNSearchResultReady resultReady, GNConfig config, List< GNAlbumIdAttributes > attributeList)
static void searchByFingerprint (GNSearchResultReady resultReady, GNConfig config, String fingerprintData)
static void searchByText (GNSearchResultReady resultReady, GNConfig config, String artist, String albumTitle, String trackTitle)
static void fetchByTrackId (GNSearchResultReady resultReady, GNConfig config, String trackId)
static void fetchByAlbumId (GNSearchResultReady resultReady, GNConfig config, String albumId)
static void searchByLyricFragment (GNSearchResultReady resultReady, GNConfig config, String lyricFragment, String artist)
static void cancel (GNFingerprintResultReady resultReady)
static void cancel (GNSearchResultReady resultReady)
Detailed Description
This class contains the operations that can be performed by the Mobile Client. Each operation is implemented as a static method.
There are three types of operations provided:
Audio recognition operations
Fingerprint generation operations
Search operations
To invoke an operation call the associated method. While an operation is running progress notifications can be received by the application. When an operation completes, results are delivered via a Result Ready Object. Operations can be canceled.
For more information, see the Mobile Client Implementation Guide.
Definition at line 45 of file GNOperations.java.
Member Function Documentation
static void com.gracenote.mmid.MobileSDK.GNOperations.albumIdDirectory (GNSearchResultReady resultReady, GNConfig config, String directoryPath) static
Scans directory for AlbumId.
Parameters
resultReady Result Ready Object instance
config Operation configuration
directoryPath Directory path
Definition at line 1952 of file GNOperations.java.
References com.gracenote.mmid.MobileSDK.GNResult.AlbumIdFailure, com.gracenote.mmid.MobileSDK.GNConfig.getBooleanProperty(), and com.gracenote.mmid.MobileSDK.GNSearchResultReady.GNResultReady().
static void com.gracenote.mmid.MobileSDK.GNOperations.albumIdFile (GNSearchResultReady resultReady, GNConfig config, List< String > filePaths) static
Scans list of files for AlbumId.
Parameters
resultReady Result Ready Object instance
config Operation configuration
filePaths List of files
Definition at line 1907 of file GNOperations.java.
References com.gracenote.mmid.MobileSDK.GNResult.AlbumIdFailure, com.gracenote.mmid.MobileSDK.GNResult.AlbumIdNoMatchStatus, com.gracenote.mmid.MobileSDK.GNConfig.getBooleanProperty(), and com.gracenote.mmid.MobileSDK.GNSearchResultReady.GNResultReady().
static void com.gracenote.mmid.MobileSDK.GNOperations.albumIdList (GNSearchResultReady resultReady, GNConfig config, List< GNAlbumIdAttributes > attributeList) static
Scans file list for AlbumId.
Parameters
resultReady Result Ready Object instance
config Operation configuration
attributeList List of type GNAlbumIdAttributes
Definition at line 1991 of file GNOperations.java.
References com.gracenote.mmid.MobileSDK.GNResult.AlbumIdFailure, com.gracenote.mmid.MobileSDK.GNConfig.getBooleanProperty(), and com.gracenote.mmid.MobileSDK.GNSearchResultReady.GNResultReady().
static void com.gracenote.mmid.MobileSDK.GNOperations.cancel (GNFingerprintResultReady resultReady) static
Cancels a fingerprint generation operation that is currently running.
Parameters
resultReady Result Ready Object instance that was provided to the operation when it was invoked.
Definition at line 2300 of file GNOperations.java.
Referenced by com.gracenote.mmid.MobileSDK.GNRecognizeStream.stopSession().
static void com.gracenote.mmid.MobileSDK.GNOperations.cancel (GNSearchResultReady resultReady) static
Cancels a search operation that is currently running.
Parameters
resultReady Result Ready Object instance that was provided to the operation when it was invoked.
Definition at line 2314 of file GNOperations.java.
static void com.gracenote.mmid.MobileSDK.GNOperations.fetchByAlbumId (GNSearchResultReady resultReady, GNConfig config, String albumId) static
Searches Gracenote's database using album Id previously obtained by a search operation.
Parameters
resultReady Result Ready Object instance
config Operation configuration
albumId GN_ID of the album
Definition at line 2168 of file GNOperations.java.
References com.gracenote.mmid.MobileSDK.GNSearchResultReady.GNResultReady(), and com.gracenote.mmid.MobileSDK.GNResult.WSAlbumFetchNoMatchStatus.
static void com.gracenote.mmid.MobileSDK.GNOperations.fetchByTrackId (GNSearchResultReady resultReady, GNConfig config, String trackId) static
Searches Gracenote's database using track Id previously obtained by a search operation.
Parameters
resultReady Result Ready Object instance
config Operation configuration
trackId GN_ID of the track
Definition at line 2133 of file GNOperations.java.
References com.gracenote.mmid.MobileSDK.GNSearchResultReady.GNResultReady(), and com.gracenote.mmid.MobileSDK.GNResult.WSAlbumFetchNoMatchStatus.
static void com.gracenote.mmid.MobileSDK.GNOperations.fingerprintMIDFileFromFile (GNFingerprintResultReady resultReady, GNConfig config, String filename) static
Generates a fingerprint for an audio file. The generated fingerprint can be used to search Gracenote's database for matches using Gracenote's MID-File product.
To process the audio file, Mobile Client requires write access to the directory where the audio file is stored. The storage media that contains the audio file must also have memory available for Mobile Client to use. The required space is estimated at 4Mb for fingerprinting a single file and up to 20Mb for fingerprinting multiple files concurrently.
Parameters
resultReady Result Ready Object instance
config Operation configuration
filename Name and path of the audio file
Definition at line 1762 of file GNOperations.java.
static void com.gracenote.mmid.MobileSDK.GNOperations.fingerprintMIDFileFromPcm (GNFingerprintResultReady resultReady, GNConfig config, GNSampleBuffer sampleBuffer) static
Generates a fingerprint for a PCM audio sample. The generated fingerprint can be used to search Gracenote's database for matches using Gracenote's MID-File product.
Parameters
resultReady Result Ready Object instance
config Operation configuration
sampleBuffer Buffer object containing the PCM audio sample
Definition at line 1724 of file GNOperations.java.
static void com.gracenote.mmid.MobileSDK.GNOperations.fingerprintMIDStreamFromMic (GNFingerprintResultReady resultReady, GNConfig config) static
Records audio from the microphone and generates a fingerprint. The generated fingerprint can be used to search Gracenote's database for matches using Gracenote's MID-Stream product.
Parameters
resultReady Result Ready Object instance
config Operation configuration
Definition at line 1665 of file GNOperations.java.
static void com.gracenote.mmid.MobileSDK.GNOperations.fingerprintMIDStreamFromPcm (GNFingerprintResultReady resultReady, GNConfig config, GNSampleBuffer sampleBuffer) static
Generates a fingerprint for a PCM audio sample. The generated fingerprint can be used to search Gracenote's database for matches using Gracenote's MID-Stream product.
Parameters
resultReady Result Ready Object instance
config Operation configuration
sampleBuffer Buffer object containing the PCM audio sample
Definition at line 1694 of file GNOperations.java.
static void com.gracenote.mmid.MobileSDK.GNOperations.recognizeMIDFileFromFile (GNSearchResultReady resultReady, GNConfig config, String filename) static
Recognizes an audio file using Gracenote's MID-File product.
To process the audio file, Mobile Client requires write access to the directory where the audio file is stored. The storage media that contains the audio file must also have memory available for Mobile Client to use. The required space is estimated at 4Mb for recognizing a single file and up to 20Mb for recognizing multiple files concurrently.
Parameters
resultReady Result Ready Object instance
config Operation configuration
filename Name and path of the audio file
Definition at line 1879 of file GNOperations.java.
static void com.gracenote.mmid.MobileSDK.GNOperations.recognizeMIDFileFromPcm (GNSearchResultReady resultReady, GNConfig config, GNSampleBuffer sampleBuffer) static
Recognizes a PCM audio sample using Gracenote's MID-File product.
Parameters
resultReady Result Ready Object instance
config Operation configuration
sampleBuffer Buffer object containing the PCM audio sample
Definition at line 1844 of file GNOperations.java.
static void com.gracenote.mmid.MobileSDK.GNOperations.recognizeMIDStreamFromMic (GNSearchResultReady resultReady, GNConfig config) static
Records audio from the microphone and recognizes it using Gracenote's MID-Stream product.
Parameters
resultReady Result Ready Object instance
config Operation configuration
Definition at line 1789 of file GNOperations.java.
static void com.gracenote.mmid.MobileSDK.GNOperations.recognizeMIDStreamFromPcm (GNSearchResultReady resultReady, GNConfig config, GNSampleBuffer sampleBuffer) static
Recognizes a PCM audio sample using Gracenote's MID-Stream product.
Parameters
resultReady Result Ready Object instance
config Operation configuration
sampleBuffer Buffer object containing the PCM audio sample
Definition at line 1816 of file GNOperations.java.
static void com.gracenote.mmid.MobileSDK.GNOperations.searchByFingerprint (GNSearchResultReady resultReady, GNConfig config, String fingerprintData) static
Searches Gracenote's database for matches to a fingerprint previously generated by a fingerprint generation operation.
Parameters
resultReady Result Ready Object instance
config Operation configuration
fingerprintData Fingerprint as generated by previous operation
Definition at line 2061 of file GNOperations.java.
static void com.gracenote.mmid.MobileSDK.GNOperations.searchByLyricFragment (GNSearchResultReady resultReady, GNConfig config, String lyricFragment, String artist) static
Searches Gracenote's database for matches to artist name and lyric fragment. Artist name is not required. For best results, provide artist name where possible.
Parameters
resultReady Result Ready Object instance
config Operation configuration
lyricFragment Fragment of track lyrics
artist Name of the artist
Definition at line 2206 of file GNOperations.java.
References com.gracenote.mmid.MobileSDK.GNSearchResultReady.GNResultReady(), and com.gracenote.mmid.MobileSDK.GNResult.WSLyricFragmentSearchNoMatchStatus.
static void com.gracenote.mmid.MobileSDK.GNOperations.searchByText (GNSearchResultReady resultReady, GNConfig config, String artist, String albumTitle, String trackTitle) static
Searches Gracenote's database for matches to artist name, album title, and track title. Not all fields are required. For best results, provide as many fields as possible.
Parameters
resultReady Result Ready Object instance
config Operation configuration
artist Name of the artist
albumTitle Title of the album
trackTitle Title of the track
Definition at line 2096 of file GNOperations.java.
References com.gracenote.mmid.MobileSDK.GNSearchResultReady.GNResultReady(), and com.gracenote.mmid.MobileSDK.GNResult.WSTextSearchNoMatchStatus.
How can we improve this topic?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Mon Jun 3 2013 13:26:05.