Mobile Client for Android: com.gracenote.mmid.MobileSDK.GNAudioSourceMic Class Reference
com.gracenote.mmid.MobileSDK.GNAudioSourceMic Class Reference
Public Member Functions
GNAudioSourceMic (GNAudioConfig audioConfig, GNAudioSourceDelegate inAudioSourceMicDelegate)
void startRecording () throws Exception
void stopRecording ()
Detailed Description
The GNAudioSourceMic class manages resources for applications to stream audio from
the platform's audio input hardware. The application receives the recorded audio (PCM-encoded)
by implementing the GNAudioSourceMicDelegate interface.
Definition at line 35 of file GNAudioSourceMic.java.
Constructor & Destructor Documentation
com.gracenote.mmid.MobileSDK.GNAudioSourceMic.GNAudioSourceMic (GNAudioConfig audioConfig, GNAudioSourceDelegate inAudioSourceMicDelegate)
Acquires audio input hardware resource and initializes it as specified by audioConfig.
Below are the limitations to the audio configuration parameters supported:
number of channels: 1 or 2, otherwise the platform's default channel configuration is used
bytes per sample: 1 or 2, otherwise 2 is used by default
Parameters
audioConfig
                            configuration object specifying audio data format
inAudioSourceMicDelegate
                            object which implements the GNAudioSourceDelegate interface to receive recorded data
Definition at line 95 of file GNAudioSourceMic.java.
References com.gracenote.mmid.MobileSDK.GNAudioConfig.getBytesPerSample(), com.gracenote.mmid.MobileSDK.GNAudioConfig.getNumChannels(), and com.gracenote.mmid.MobileSDK.GNAudioConfig.getSampleRate().
Member Function Documentation
void com.gracenote.mmid.MobileSDK.GNAudioSourceMic.startRecording () throws Exception
Starts recording, will re-acquire audio input hardware resources if it has been previously released
Exceptions
Exception
                            if microphone initialization failed, either the hardware
                            resource could not be acquired or the passed audio configuration parameters are not supported
Definition at line 211 of file GNAudioSourceMic.java.
void com.gracenote.mmid.MobileSDK.GNAudioSourceMic.stopRecording ()
Stops recording and releases the audio input hardware resource
Definition at line 427 of file GNAudioSourceMic.java.
How can we improve this topic?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Mon Jun 3 2013 13:26:05.