Mobile Client for Android: com.gracenote.mmid.MobileSDK.GNConfig Class Reference
com.gracenote.mmid.MobileSDK.GNConfig Class Reference
Public Member Functions
void loadCache (String bundleFilePath)
boolean clearCache ()
void setProperty (String key, String value)
String getProperty (String key)
boolean getBooleanProperty (String key)
Static Public Member Functions
static GNConfig init (String inClientId, Context inContext)
Protected Member Functions
Object clone () throws CloneNotSupportedException
Static Protected Member Functions
static GNConfig getDefaultConfig ()
Protected Attributes
GNLocalLookUp gnLocalLookUp = null
Detailed Description
The GNConfig module implements a configuration object required when invoking an operation via the GNOperations module. You invoke GNConfig.init() and pass a Client Id String and an Android Context to create a GNConfig object.
Your Client Id is provided by your Gracenote Professional Services representative.
In a typical application the default configuration object can be used. If required, you can change the application-wide configuration properties by invoking the GNConfig.setProperty() method on the configuration object instance returned by GNConfig.init().
To create a custom set of configuration options that apply to a specific invocation of an operation, create a copy of the GNConfig object instance using its clone() interface. Then customize the properties on the created object instance and provide it when invoking operations that require the customized property settings.
Supported Properties:
Property Type Access Default
Description
"clientId"
String
Read only
""
Client Id supplied when GNConfig.init() is called to create the object.
"content.albumId.queryPreference.useFingerprint"
Boolean String
Read/Write
"1"
When set to "1", AlbumId query uses fingerprints. When set to "0", AlbumId query does not use fingerprints.
"content.albumId.queryPreference.useGN_ID"
Boolean String
Read/Write
"1"
When set to "1", AlbumId query uses GN_ID. When set to "0", AlbumId query does not use GN_ID.
"content.albumId.queryPreference.useTagData"
Boolean String
Read/Write
"1"
When set to "1", AlbumId query uses ID3 tag data. When set to "0", AlbumId query will not include ID3 tag data for lookup.
"content.artistType"
Boolean String
Read/Write
"0"
When set to "1", Mobile Client returns artist type (where available) in the result.
"content.artistType.level"
String
Read/Write
"NONE"
When set to "DEFAULT", Mobile Client returns a single, default artist type descriptor in the result. When set to "EXTENDED", Mobile Client returns multiple levels of artist type descriptors in the result.
"content.contributor.biography"
Boolean String
Read/Write
"0"
When set to "1", Mobile Client returns contributor biography (where available); only applicable to products that return a single best match.
"content.contributor.images"
Boolean String
Read/Write
"0"
When set to "1", Mobile Client returns a contributor image (where available); only applicable to products that return a single best match.
"content.country"
String
Read/Write
""
Mobile Client delivers metadata for the specified country where available. All country codes specified by ISO 3166-1 alpha-3 are supported.
"content.coverArt"
Boolean String
Read/Write
"0"
When set to "1", Mobile Client returns cover art (where available); only applicable to products that return a single best match. When set to "0", no coverArt will be returned in result.
"content.coverArt.genreCoverArt"
Boolean String
Read/Write
"1"
When set to "1", Mobile Client returns genre cover art (where available); only applicable to products that return a single best match.
"content.coverArt.sizePreference"
Comma Separated String
Read/Write
"SMALL,MEDIUM,THUMBNAIL,LARGE,XLARGE"
Cover art can be returned in various sizes depending on availability and the preferences set by the application. You can set the preferences of your application via this configuration parameter.
List the cover art sizes in a comma-separated list in order of preference.
If an invalid size preference is provided, the default is used.
"content.era"
Boolean String
Read/Write
"0"
When set to "1", Mobile Client returns era (where available) in the result.
"content.era.level"
String
Read/Write
"NONE"
When set to "DEFAULT", Mobile Client returns a single, default era descriptor in the result. When set to "EXTENDED", Mobile Client returns multiple levels of era descriptors in the result.
"content.genre.level"
String
Read/Write
"DEFAULT"
When set to "DEFAULT", Mobile Client returns a single, default genre descriptor in the result. When set to "EXTENDED", Mobile Client returns multiple levels of genre descriptors in the result.
"content.lang"
String
Read/Write
""
(no specific language)
Defines the preferred language in which results are returned. Results are returned in the selected language where available.
Check with Gracenote Professional Services for the full set of supported ISO 639-2 languages and codes.
Example language values are:
"eng" - English
"kor" - Korean
"ara" - Arabic
"bul" - Bulgarian
"chi" - Chinese (Simplified)
"qtb" - Chinese (Simplified)
"hrv" - Croatian
"scr" - Croatian
"cze" - Czech
"dan" - Danish
"dut" - Dutch
"epo" - Esperanto
"per" - Persian
"fin" - Finnish
"fre" - French
"ger" - German
"gre" - Greek
"hun" - Hungarian
"ind" - Indonesian
"ita" - Italian
"jpn" - Japanese
"qtd" - Chinese (Traditional)
"nor" - Norwegian
"pol" - Polish
"rum" - Romanian
"rus" - Russian
"srp" - Serbian
"scc" - Serbian
"slo" - Slovak
"spa" - Spanish
"swe" - Swedish
"tha" - Thai
"tur" - Turkish
"vie" - Vietnamese
"content.link.preferredSource"
String
Read/Write
""
(no specific preferred link)
Indicates the preferred Link identifier source when performing an audio recognition request that returns a single best match. Does not apply to AlbumId.
"content.mood"
Boolean String
Read/Write
"0"
When set to "1", Mobile Client returns mood (where available) in the result.
"content.mood.level"
String
Read/Write
"NONE"
When set to "DEFAULT", Mobile Client returns a single, default mood descriptor in the result. When set to "EXTENDED", Mobile Client returns multiple levels of mood descriptors in the result.
"content.musicId.queryPreference.singleBestMatch"
Boolean String
Read/Write
"1"
Mobile Client returns the single best match in the result. When set to "0", Mobile Client may return multiple matches in result. Only applicable to MIDF and MID stream operations.
"content.origin"
Boolean String
Read/Write
"0"
When set to "1", Mobile Client returns origin (where available) in the result.
"content.origin.level"
String
Read/Write
"NONE"
When set to "DEFAULT", Mobile Client returns a single, default origin descriptor in the result. When set to "EXTENDED", Mobile Client returns multiple levels of origin descriptors in the result.
"content.review"
Boolean String
Read/Write
"0"
When set to "1", Mobile Client returns album (content) review (where available) in returned result; only applicable to products that return a single best match.
"content.tempo"
Boolean String
Read/Write
"0"
When set to "1", Mobile Client returns tempo (where available) in the result.
"content.tempo.level"
String
Read/Write
"NONE"
When set to "DEFAULT", Mobile Client returns a single, default tempo descriptor in the result. When set to "EXTENDED", Mobile Client returns multiple levels of tempo descriptors in the result.
"content.allowFullResponse"
Boolean String
Read/Write
"0"
When set to "1", Mobile Client returns a full response when single best is true.
"debugEnabled"
Boolean String
Read/Write
"0"
When set to "1", the debug information is written to the file specified by the "debugLog" property.
"debugLog"
String
Read/Write
"/sdcard/gracenote"
Path of the debug log file created when property "debugEnabled" is set to "1".
"version"
String
Read only Mobile Client Version
Version information for this release.
Definition at line 291 of file GNConfig.java.
Member Function Documentation
boolean com.gracenote.mmid.MobileSDK.GNConfig.clearCache ()
Removes cache previously loaded, releases memory storing fingerprint data
Returns
true if operation successful
Definition at line 507 of file GNConfig.java.
References com.gracenote.mmid.MobileSDK.GNConfig.gnLocalLookUp.
Object com.gracenote.mmid.MobileSDK.GNConfig.clone () throws CloneNotSupportedException protected
Returns a copy of the current configuration. This method is useful when a specific operation needs to be performed with a non-default option. You create a copy of the default configuration, change the property on the copy, and then pass the copy into a GNOperations method as the config argument.
Definition at line 572 of file GNConfig.java.
boolean com.gracenote.mmid.MobileSDK.GNConfig.getBooleanProperty (String key)
Simplifies testing of configuration object properties of type "Boolean String".
This method can be used to read configuration object properties of type "Boolean String". If this method is used to obtain the value of a property that is of a type other than "Boolean String", an exception is thrown.
Parameters
key Property name
Returns
Value of the property, true for "1", "true" or "True"; false for "0", "false" or "False".
Definition at line 685 of file GNConfig.java.
References com.gracenote.mmid.MobileSDK.GNConfig.getProperty().
Referenced by com.gracenote.mmid.MobileSDK.GNOperations.albumIdDirectory(), com.gracenote.mmid.MobileSDK.GNOperations.albumIdFile(), com.gracenote.mmid.MobileSDK.GNOperations.albumIdList(), and com.gracenote.mmid.MobileSDK.GNRecognizeStream.writeBytes().
static GNConfig com.gracenote.mmid.MobileSDK.GNConfig.getDefaultConfig () static protected
Returns the current configuration. Do not use this configuration to get the value of public properties in an operation. Only use it for private properties, executing and pending in the queue that will never change after defaultConfig inits.
Definition at line 596 of file GNConfig.java.
String com.gracenote.mmid.MobileSDK.GNConfig.getProperty (String key)
Returns the value for a configuration object property.
Parameters
key Property name
Returns
String Property value
Definition at line 661 of file GNConfig.java.
Referenced by com.gracenote.mmid.MobileSDK.GNConfig.getBooleanProperty(), com.gracenote.mmid.MobileSDK.GNConfig.init(), and com.gracenote.mmid.MobileSDK.GNRecognizeStream.writeBytes().
static GNConfig com.gracenote.mmid.MobileSDK.GNConfig.init (String inClientId, Context inContext) static
Creates a configuration object that is used when invoking a Mobile Client operation via the GNOperations module.
Configuration objects must be created prior to invoking any Mobile Client operations. Create a configuration object by invoking this method. Be sure to store the returned object.
You must provide a Client Id and an Android Context. Your Client Id is provided by your Gracenote Professional Services representative.
The provided Context can be any Android Context; ensure it is valid for the life of the application. For example, an Activity Context may not be valid for the duration of the application; once the Activity object is destroyed, Mobile Client will generate an exception when it next attempts to access the Context object. Gracenote recommends providing the Application Context, which can be obtained from an Activity object. See the Sample Application for a complete example of creating and using a configuration object.
Returns
Configuration object instance initialized with the default property values.
Definition at line 540 of file GNConfig.java.
References com.gracenote.mmid.MobileSDK.GNConfig.getProperty().
void com.gracenote.mmid.MobileSDK.GNConfig.loadCache (String bundleFilePath)
Set up database for local lookup
Parameters
bundleFilePath file path of bundle
Definition at line 486 of file GNConfig.java.
References com.gracenote.mmid.MobileSDK.GNConfig.gnLocalLookUp.
void com.gracenote.mmid.MobileSDK.GNConfig.setProperty (String key, String value)
Sets the value of a configuration object property.
Parameters
key Property name
value Property value as a String. For properties of type "Boolean String" the value can be "1", "true" or "True", or "0", "false" or "False".
Definition at line 608 of file GNConfig.java.
Member Data Documentation
GNLocalLookUp com.gracenote.mmid.MobileSDK.GNConfig.gnLocalLookUp = null protected
Definition at line 303 of file GNConfig.java.
Referenced by com.gracenote.mmid.MobileSDK.GNConfig.clearCache(), and com.gracenote.mmid.MobileSDK.GNConfig.loadCache().
How can we improve this topic?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Mon Jun 3 2013 13:26:05.