Mobile Client for Android: com.gracenote.mmid.MobileSDK.GNRecognizeStream Class Reference
com.gracenote.mmid.MobileSDK.GNRecognizeStream Class Reference
Public Member Functions
GNRecognizeStream (GNConfig config)
GNAudioConfig getGNAudioConfig ()
void startSession (GNSearchResultReady resultReady, GNAudioConfig audioConfig)
void stopSession ()
void cancelIdNow ()
void writeBytes (byte[] data)
void idNow ()
Detailed Description
This class processes an audio stream for recognition.
The input stream is received via the writeBytes method. Results are returned
via a GNResultReady object.
Definition at line 249 of file GNRecognizeStream.java.
Constructor & Destructor Documentation
com.gracenote.mmid.MobileSDK.GNRecognizeStream.GNRecognizeStream (GNConfig config)
Initializes a new GNRecognizeStream object with the Application's GNConfig object and GNSearchResultReady
Parameters
config Operation configuration
Definition at line 297 of file GNRecognizeStream.java.
Member Function Documentation
void com.gracenote.mmid.MobileSDK.GNRecognizeStream.cancelIdNow ()
Cancels an IdNow() call currently in progress.
Definition at line 503 of file GNRecognizeStream.java.
GNAudioConfig com.gracenote.mmid.MobileSDK.GNRecognizeStream.getGNAudioConfig ()
Returns
The audio configuration object passed to the startSession call
Definition at line 323 of file GNRecognizeStream.java.
void com.gracenote.mmid.MobileSDK.GNRecognizeStream.idNow ()
Performs audio stream recognition,
storing results in the Result Ready object passed to the startSession call.
Definition at line 621 of file GNRecognizeStream.java.
void com.gracenote.mmid.MobileSDK.GNRecognizeStream.startSession (GNSearchResultReady resultReady, GNAudioConfig audioConfig)
Starts the stream processing session by initializing objects needed
to allow writeBytes to continuously feed audio samples to a buffer.
Note that no recognition is performed until idNow() is called.
Parameters
audioConfig
                            audio configuration instance used to calculate internal streaming buffer size
resultReady
                            Result Ready Object instance used to store recognition results
Definition at line 349 of file GNRecognizeStream.java.
References com.gracenote.mmid.MobileSDK.GNAudioConfig.getBytesPerSample(), and com.gracenote.mmid.MobileSDK.GNAudioConfig.getSampleRate().
void com.gracenote.mmid.MobileSDK.GNRecognizeStream.stopSession ()
Stops the stream processing session,
releasing all resources allocated by startSession()
Definition at line 423 of file GNRecognizeStream.java.
References com.gracenote.mmid.MobileSDK.GNOperations.cancel().
void com.gracenote.mmid.MobileSDK.GNRecognizeStream.writeBytes (byte[] data)
Writes PCM audio data to the GNRecognizeStream object. The PCM data should be of the
same format specified in the GNAudioConfig object. Buffers of consistent length representing
less than a second of PCM data are best.
Parameters
data
                    buffer containing PCM data
Definition at line 527 of file GNRecognizeStream.java.
References com.gracenote.mmid.MobileSDK.GNStatusEnum.ERROR, com.gracenote.mmid.MobileSDK.GNConfig.getBooleanProperty(), and com.gracenote.mmid.MobileSDK.GNConfig.getProperty().
How can we improve this topic?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Mon Jun 3 2013 13:26:06.