Mobile Client for Android: com.gracenote.mmid.MobileSDK.GNAudioConfig Class Reference
com.gracenote.mmid.MobileSDK.GNAudioConfig Class Reference
Public Member Functions
GNAudioConfig (int inSampleRate, int inBytesPerSample, int inNumChannel)
int getBytesPerSample ()
int getNumChannels ()
int getSampleRate ()
Detailed Description
This class specifies the audio data format based on 3 parameters:
the number of bytes per sample, the sampling rate, and number of channels.
Definition at line 19 of file GNAudioConfig.java.
Constructor & Destructor Documentation
com.gracenote.mmid.MobileSDK.GNAudioConfig.GNAudioConfig (int inSampleRate, int inBytesPerSample, int inNumChannel)
Constructs the audio configuration object
Parameters
inSampleRate
                            sampling rate in Hertz
inBytesPerSample
                            number of bytes per sample
inNumChannel
                            number of channels present
Definition at line 47 of file GNAudioConfig.java.
Member Function Documentation
int com.gracenote.mmid.MobileSDK.GNAudioConfig.getBytesPerSample ()
Returns
the number of bytes per sample
Definition at line 67 of file GNAudioConfig.java.
Referenced by com.gracenote.mmid.MobileSDK.GNAudioSourceMic.GNAudioSourceMic(), and com.gracenote.mmid.MobileSDK.GNRecognizeStream.startSession().
int com.gracenote.mmid.MobileSDK.GNAudioConfig.getNumChannels ()
Returns
the number of channels
Definition at line 81 of file GNAudioConfig.java.
Referenced by com.gracenote.mmid.MobileSDK.GNAudioSourceMic.GNAudioSourceMic().
int com.gracenote.mmid.MobileSDK.GNAudioConfig.getSampleRate ()
Returns
sampling rate
Definition at line 95 of file GNAudioConfig.java.
Referenced by com.gracenote.mmid.MobileSDK.GNAudioSourceMic.GNAudioSourceMic(), and com.gracenote.mmid.MobileSDK.GNRecognizeStream.startSession().
How can we improve this topic?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Mon Jun 3 2013 13:26:05.