Mobile Client for Android: com.gracenote.mmid.MobileSDK.GNImage Class Reference
com.gracenote.mmid.MobileSDK.GNImage Class Reference
Public Member Functions
GNImage (byte[] inData, String inSize, String inMimeType)
GNImage (String inUrl)
byte[] getData ()
String getSize ()
String getMimeType ()
String getUrl ()
String toString ()
Detailed Description
Container class for artist images.
Definition at line 15 of file GNImage.java.
Constructor & Destructor Documentation
com.gracenote.mmid.MobileSDK.GNImage.GNImage (byte[] inData, String inSize, String inMimeType)
Definition at line 29 of file GNImage.java.
com.gracenote.mmid.MobileSDK.GNImage.GNImage (String inUrl)
Definition at line 47 of file GNImage.java.
Member Function Documentation
byte [] com.gracenote.mmid.MobileSDK.GNImage.getData ()
Returns the image data in a standard
image format (such as JPEG) in serialized form.
Returns
Image data
Definition at line 65 of file GNImage.java.
Referenced by com.gracenote.mmid.MobileSDK.GNCoverArt.toString().
String com.gracenote.mmid.MobileSDK.GNImage.getMimeType ()
Returns the image MIME type, such as "image/jpeg". The MIME type can
be used to determine how the image data is processed by the application.
Returns
Image MIME type
Definition at line 107 of file GNImage.java.
Referenced by com.gracenote.mmid.MobileSDK.GNCoverArt.toString().
String com.gracenote.mmid.MobileSDK.GNImage.getSize ()
Returns the size of the image. The size can be specified as either
SMALL, MEDIUM, THUMBNAIL, LARGE, or XLARGE.
Returns
Image size as a string
Definition at line 91 of file GNImage.java.
Referenced by com.gracenote.mmid.MobileSDK.GNCoverArt.toString().
String com.gracenote.mmid.MobileSDK.GNImage.getUrl ()
Returns the URL for the image. The URL can be used to download images.
Returns
URL
Definition at line 121 of file GNImage.java.
String com.gracenote.mmid.MobileSDK.GNImage.toString ()
Returns a string that describes the GNImage instance.
Returns
String describing the GNImage instance
Definition at line 137 of file GNImage.java.
How can we improve this topic?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Mon Jun 3 2013 13:26:05.